// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: PyroVision

#ifndef UI_INFO_H
#define UI_INFO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Info
extern void ui_Info_screen_init(void);
extern void ui_Info_screen_destroy(void);
extern void ui_event_Info(lv_event_t * e);
extern lv_obj_t * ui_Info;
extern lv_obj_t * ui_Panel_Info_Header;
extern lv_obj_t * ui_Label_Info_Header;
extern lv_obj_t * ui_Panel_Info_Content;
extern lv_obj_t * ui_Panel_Device;
extern lv_obj_t * ui_Label_Info_Device;
extern lv_obj_t * ui_Container_Info_Device;
extern lv_obj_t * ui_Info_Container4;
extern lv_obj_t * ui_Label_Info_MAC_Name;
extern lv_obj_t * ui_Label_Info_IP_Name;
extern lv_obj_t * ui_Info_Container5;
extern lv_obj_t * ui_Label_Info_MAC;
extern lv_obj_t * ui_Label_Info_IP;
extern lv_obj_t * ui_Panel_Battery;
extern lv_obj_t * ui_Label_Info_Battery;
extern lv_obj_t * ui_Container_Battery;
extern lv_obj_t * ui_Info_Container2;
extern lv_obj_t * ui_Label_Info_Battery_Status_Name;
extern lv_obj_t * ui_Label_Info_Battery_Voltage_Name;
extern lv_obj_t * ui_Label_Info_Battery_Remaining_Name;
extern lv_obj_t * ui_Info_Container3;
extern lv_obj_t * ui_Label_Info_Battery_Status;
extern lv_obj_t * ui_Label_Info_Battery_Voltage;
extern lv_obj_t * ui_Label_Info_Battery_Remaining;
extern lv_obj_t * ui_Info_Bar2;
extern lv_obj_t * ui_Panel_Lepton;
extern lv_obj_t * ui_Label_Info_Lepton;
extern lv_obj_t * ui_Container_Lepton;
extern lv_obj_t * ui_Info_Container1;
extern lv_obj_t * ui_Label_Info_Lepton_Serial_Name;
extern lv_obj_t * ui_Label_Info_Lepton_Part_Name;
extern lv_obj_t * ui_Label_Info_Lepton_Revision_Name;
extern lv_obj_t * ui_Label_Info_Lepton_Uptime_Name;
extern lv_obj_t * ui_Label_Info_Lepton_FPA_Name;
extern lv_obj_t * ui_Label_Info_Lepton_AUX_Name;
extern lv_obj_t * ui_Info_Container7;
extern lv_obj_t * ui_Label_Info_Lepton_Serial;
extern lv_obj_t * ui_Label_Info_Lepton_Part;
extern lv_obj_t * ui_Label_Info_Lepton_Revision;
extern lv_obj_t * ui_Label_Info_Lepton_Uptime;
extern lv_obj_t * ui_Label_Info_Lepton_FPA;
extern lv_obj_t * ui_Label_Info_Lepton_AUX;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

