// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: PyroVision

#include "../ui.h"

lv_obj_t * ui_Info = NULL;
lv_obj_t * ui_Panel_Info_Header = NULL;
lv_obj_t * ui_Label_Info_Header = NULL;
lv_obj_t * ui_Panel_Info_Content = NULL;
lv_obj_t * ui_Panel_Device = NULL;
lv_obj_t * ui_Label_Info_Device = NULL;
lv_obj_t * ui_Container_Info_Device = NULL;
lv_obj_t * ui_Info_Container4 = NULL;
lv_obj_t * ui_Label_Info_MAC_Name = NULL;
lv_obj_t * ui_Label_Info_IP_Name = NULL;
lv_obj_t * ui_Info_Container5 = NULL;
lv_obj_t * ui_Label_Info_MAC = NULL;
lv_obj_t * ui_Label_Info_IP = NULL;
lv_obj_t * ui_Panel_Battery = NULL;
lv_obj_t * ui_Label_Info_Battery = NULL;
lv_obj_t * ui_Container_Battery = NULL;
lv_obj_t * ui_Info_Container2 = NULL;
lv_obj_t * ui_Label_Info_Battery_Status_Name = NULL;
lv_obj_t * ui_Label_Info_Battery_Voltage_Name = NULL;
lv_obj_t * ui_Label_Info_Battery_Remaining_Name = NULL;
lv_obj_t * ui_Info_Container3 = NULL;
lv_obj_t * ui_Label_Info_Battery_Status = NULL;
lv_obj_t * ui_Label_Info_Battery_Voltage = NULL;
lv_obj_t * ui_Label_Info_Battery_Remaining = NULL;
lv_obj_t * ui_Info_Bar2 = NULL;
lv_obj_t * ui_Panel_Lepton = NULL;
lv_obj_t * ui_Label_Info_Lepton = NULL;
lv_obj_t * ui_Container_Lepton = NULL;
lv_obj_t * ui_Info_Container1 = NULL;
lv_obj_t * ui_Label_Info_Lepton_Serial_Name = NULL;
lv_obj_t * ui_Label_Info_Lepton_Part_Name = NULL;
lv_obj_t * ui_Label_Info_Lepton_Revision_Name = NULL;
lv_obj_t * ui_Label_Info_Lepton_Uptime_Name = NULL;
lv_obj_t * ui_Label_Info_Lepton_FPA_Name = NULL;
lv_obj_t * ui_Label_Info_Lepton_AUX_Name = NULL;
lv_obj_t * ui_Info_Container7 = NULL;
lv_obj_t * ui_Label_Info_Lepton_Serial = NULL;
lv_obj_t * ui_Label_Info_Lepton_Part = NULL;
lv_obj_t * ui_Label_Info_Lepton_Revision = NULL;
lv_obj_t * ui_Label_Info_Lepton_Uptime = NULL;
lv_obj_t * ui_Label_Info_Lepton_FPA = NULL;
lv_obj_t * ui_Label_Info_Lepton_AUX = NULL;
// event funtions
void ui_event_Info(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Main_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ScreenInfoLoaded(e);
    }
}

// build funtions

void ui_Info_screen_init(void)
{
    ui_Info = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Info, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Info, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Info_Header = lv_obj_create(ui_Info);
    lv_obj_set_width(ui_Panel_Info_Header, 320);
    lv_obj_set_height(ui_Panel_Info_Header, 30);
    lv_obj_set_x(ui_Panel_Info_Header, 1);
    lv_obj_set_y(ui_Panel_Info_Header, 1);
    lv_obj_set_align(ui_Panel_Info_Header, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Panel_Info_Header,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Panel_Info_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_Info_Header, lv_color_hex(0x7B3FF0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Info_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_Info_Header, lv_color_hex(0x7B3FF0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_Info_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_Header = lv_label_create(ui_Panel_Info_Header);
    lv_obj_set_width(ui_Label_Info_Header, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Info_Header, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_Header, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Header, "SYSTEM INFORMATION");
    lv_obj_remove_flag(ui_Label_Info_Header,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Header, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Header, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Info_Content = lv_obj_create(ui_Info);
    lv_obj_set_width(ui_Panel_Info_Content, 320);
    lv_obj_set_height(ui_Panel_Info_Content, 210);
    lv_obj_set_x(ui_Panel_Info_Content, 0);
    lv_obj_set_y(ui_Panel_Info_Content, 30);
    lv_obj_set_align(ui_Panel_Info_Content, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Panel_Info_Content, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel_Info_Content, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scrollbar_mode(ui_Panel_Info_Content, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_Panel_Info_Content, LV_DIR_VER);
    lv_obj_set_style_radius(ui_Panel_Info_Content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_Info_Content, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Info_Content, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_Info_Content, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_Info_Content, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_Info_Content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_Info_Content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_Info_Content, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_Info_Content, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Panel_Info_Content, 2, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_Info_Content, lv_color_hex(0x7B3FF0), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Info_Content, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Info_Content, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Panel_Device = lv_obj_create(ui_Panel_Info_Content);
    lv_obj_set_width(ui_Panel_Device, 300);
    lv_obj_set_height(ui_Panel_Device, 100);
    lv_obj_set_align(ui_Panel_Device, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel_Device, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel_Device, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Panel_Device, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Panel_Device, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_Device, lv_color_hex(0x252525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Device, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_Device, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_Device, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_Device, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_Device, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_Device = lv_label_create(ui_Panel_Device);
    lv_obj_set_height(ui_Label_Info_Device, lv_pct(15));
    lv_obj_set_width(ui_Label_Info_Device, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Label_Info_Device, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Device, "DEVICE");
    lv_obj_remove_flag(ui_Label_Info_Device,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Device, lv_color_hex(0xB998FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Device, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Device, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_Info_Device = lv_obj_create(ui_Panel_Device);
    lv_obj_remove_style_all(ui_Container_Info_Device);
    lv_obj_set_width(ui_Container_Info_Device, lv_pct(100));
    lv_obj_set_height(ui_Container_Info_Device, lv_pct(50));
    lv_obj_set_align(ui_Container_Info_Device, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container_Info_Device, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container_Info_Device, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container_Info_Device, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container_Info_Device, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container_Info_Device, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container_Info_Device, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container_Info_Device, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Container4 = lv_obj_create(ui_Container_Info_Device);
    lv_obj_remove_style_all(ui_Info_Container4);
    lv_obj_set_width(ui_Info_Container4, lv_pct(50));
    lv_obj_set_height(ui_Info_Container4, lv_pct(100));
    lv_obj_set_align(ui_Info_Container4, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_Info_Container4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Info_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Info_Container4,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_Label_Info_MAC_Name = lv_label_create(ui_Info_Container4);
    lv_obj_set_width(ui_Label_Info_MAC_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Info_MAC_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_MAC_Name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_MAC_Name, "MAC:");
    lv_obj_remove_flag(ui_Label_Info_MAC_Name,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_MAC_Name, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_MAC_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_MAC_Name, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_MAC_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_MAC_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_MAC_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_MAC_Name, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_IP_Name = lv_label_create(ui_Info_Container4);
    lv_obj_set_width(ui_Label_Info_IP_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Info_IP_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_IP_Name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_IP_Name, "IP:");
    lv_obj_remove_flag(ui_Label_Info_IP_Name,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_IP_Name, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_IP_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_IP_Name, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_IP_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_IP_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_IP_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_IP_Name, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Container5 = lv_obj_create(ui_Container_Info_Device);
    lv_obj_remove_style_all(ui_Info_Container5);
    lv_obj_set_width(ui_Info_Container5, lv_pct(50));
    lv_obj_set_height(ui_Info_Container5, lv_pct(100));
    lv_obj_set_align(ui_Info_Container5, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_Info_Container5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Info_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_Info_Container5,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_Label_Info_MAC = lv_label_create(ui_Info_Container5);
    lv_obj_set_width(ui_Label_Info_MAC, lv_pct(100));
    lv_obj_set_height(ui_Label_Info_MAC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_MAC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_MAC, "AA:BB:CC:DD:EE:FF");
    lv_obj_remove_flag(ui_Label_Info_MAC,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_MAC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_MAC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Info_MAC, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_MAC, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_MAC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_MAC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_MAC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_MAC, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_IP = lv_label_create(ui_Info_Container5);
    lv_obj_set_width(ui_Label_Info_IP, lv_pct(100));
    lv_obj_set_height(ui_Label_Info_IP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_IP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_IP, "127.0.0.1\n");
    lv_obj_remove_flag(ui_Label_Info_IP,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_IP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_IP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Info_IP, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_IP, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_IP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_IP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_IP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_IP, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Battery = lv_obj_create(ui_Panel_Info_Content);
    lv_obj_set_width(ui_Panel_Battery, 300);
    lv_obj_set_height(ui_Panel_Battery, 100);
    lv_obj_set_align(ui_Panel_Battery, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel_Battery, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel_Battery, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Panel_Battery,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Panel_Battery, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_Battery, lv_color_hex(0x252525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Battery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_Battery, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_Battery, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_Battery, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_Battery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_Battery = lv_label_create(ui_Panel_Battery);
    lv_obj_set_height(ui_Label_Info_Battery, lv_pct(15));
    lv_obj_set_width(ui_Label_Info_Battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Label_Info_Battery, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Battery, "BATTERY");
    lv_obj_remove_flag(ui_Label_Info_Battery,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Battery, lv_color_hex(0xB998FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Battery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Battery, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_Battery = lv_obj_create(ui_Panel_Battery);
    lv_obj_remove_style_all(ui_Container_Battery);
    lv_obj_set_width(ui_Container_Battery, lv_pct(100));
    lv_obj_set_height(ui_Container_Battery, lv_pct(50));
    lv_obj_set_align(ui_Container_Battery, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container_Battery, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container_Battery, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container_Battery, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container_Battery, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container_Battery, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container_Battery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container_Battery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Container2 = lv_obj_create(ui_Container_Battery);
    lv_obj_remove_style_all(ui_Info_Container2);
    lv_obj_set_width(ui_Info_Container2, lv_pct(50));
    lv_obj_set_height(ui_Info_Container2, lv_pct(100));
    lv_obj_set_align(ui_Info_Container2, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_Info_Container2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Info_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Info_Container2,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_Label_Info_Battery_Status_Name = lv_label_create(ui_Info_Container2);
    lv_obj_set_width(ui_Label_Info_Battery_Status_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Info_Battery_Status_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_Battery_Status_Name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Battery_Status_Name, "Status:");
    lv_obj_remove_flag(ui_Label_Info_Battery_Status_Name,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Battery_Status_Name, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Battery_Status_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Battery_Status_Name, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_Battery_Status_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_Battery_Status_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_Battery_Status_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_Battery_Status_Name, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_Battery_Voltage_Name = lv_label_create(ui_Info_Container2);
    lv_obj_set_width(ui_Label_Info_Battery_Voltage_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Info_Battery_Voltage_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_Battery_Voltage_Name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Battery_Voltage_Name, "Voltage:");
    lv_obj_remove_flag(ui_Label_Info_Battery_Voltage_Name,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Battery_Voltage_Name, lv_color_hex(0x888888),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Battery_Voltage_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Battery_Voltage_Name, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_Battery_Voltage_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_Battery_Voltage_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_Battery_Voltage_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_Battery_Voltage_Name, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_Battery_Remaining_Name = lv_label_create(ui_Info_Container2);
    lv_obj_set_width(ui_Label_Info_Battery_Remaining_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Info_Battery_Remaining_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_Battery_Remaining_Name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Battery_Remaining_Name, "Remaining:");
    lv_obj_remove_flag(ui_Label_Info_Battery_Remaining_Name,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Battery_Remaining_Name, lv_color_hex(0x888888),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Battery_Remaining_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Battery_Remaining_Name, &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_Battery_Remaining_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_Battery_Remaining_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_Battery_Remaining_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_Battery_Remaining_Name, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Container3 = lv_obj_create(ui_Container_Battery);
    lv_obj_remove_style_all(ui_Info_Container3);
    lv_obj_set_width(ui_Info_Container3, lv_pct(50));
    lv_obj_set_height(ui_Info_Container3, lv_pct(100));
    lv_obj_set_align(ui_Info_Container3, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_Info_Container3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Info_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_Info_Container3,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_Label_Info_Battery_Status = lv_label_create(ui_Info_Container3);
    lv_obj_set_width(ui_Label_Info_Battery_Status, lv_pct(100));
    lv_obj_set_height(ui_Label_Info_Battery_Status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_Battery_Status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Battery_Status, "Nothing");
    lv_obj_remove_flag(ui_Label_Info_Battery_Status,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Battery_Status, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Battery_Status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Info_Battery_Status, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Battery_Status, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_Battery_Status, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_Battery_Status, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_Battery_Status, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_Battery_Status, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_Battery_Voltage = lv_label_create(ui_Info_Container3);
    lv_obj_set_width(ui_Label_Info_Battery_Voltage, lv_pct(100));
    lv_obj_set_height(ui_Label_Info_Battery_Voltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_Battery_Voltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Battery_Voltage, "4.2 V");
    lv_obj_remove_flag(ui_Label_Info_Battery_Voltage,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Battery_Voltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Battery_Voltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Info_Battery_Voltage, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Battery_Voltage, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_Battery_Voltage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_Battery_Voltage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_Battery_Voltage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_Battery_Voltage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_Battery_Remaining = lv_label_create(ui_Info_Container3);
    lv_obj_set_width(ui_Label_Info_Battery_Remaining, lv_pct(100));
    lv_obj_set_height(ui_Label_Info_Battery_Remaining, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_Battery_Remaining, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Battery_Remaining, "75%");
    lv_obj_remove_flag(ui_Label_Info_Battery_Remaining,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Battery_Remaining, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Battery_Remaining, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Info_Battery_Remaining, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Battery_Remaining, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_Battery_Remaining, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_Battery_Remaining, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_Battery_Remaining, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_Battery_Remaining, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Bar2 = lv_bar_create(ui_Panel_Battery);
    lv_bar_set_value(ui_Info_Bar2, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Info_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_Info_Bar2, 15);
    lv_obj_set_width(ui_Info_Bar2, lv_pct(100));
    lv_obj_set_align(ui_Info_Bar2, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_Info_Bar2, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Bar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Info_Bar2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Info_Bar2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Info_Bar2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Info_Bar2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Info_Bar2, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Info_Bar2, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Info_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Info_Bar2, lv_color_hex(0x61FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Info_Bar2, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Info_Bar2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Info_Bar2,
                                                                                                lv_obj_get_style_pad_right(ui_Info_Bar2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Panel_Lepton = lv_obj_create(ui_Panel_Info_Content);
    lv_obj_set_width(ui_Panel_Lepton, 300);
    lv_obj_set_height(ui_Panel_Lepton, 140);
    lv_obj_set_x(ui_Panel_Lepton, 0);
    lv_obj_set_y(ui_Panel_Lepton, 80);
    lv_obj_set_align(ui_Panel_Lepton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel_Lepton, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel_Lepton, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Panel_Lepton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Panel_Lepton, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_Lepton, lv_color_hex(0x252525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Lepton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_Lepton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_Lepton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_Lepton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_Lepton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_Lepton = lv_label_create(ui_Panel_Lepton);
    lv_obj_set_height(ui_Label_Info_Lepton, lv_pct(15));
    lv_obj_set_width(ui_Label_Info_Lepton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Label_Info_Lepton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Lepton, "LEPTON\n");
    lv_obj_remove_flag(ui_Label_Info_Lepton,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Lepton, lv_color_hex(0xB998FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Lepton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Lepton, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_Lepton = lv_obj_create(ui_Panel_Lepton);
    lv_obj_remove_style_all(ui_Container_Lepton);
    lv_obj_set_width(ui_Container_Lepton, lv_pct(100));
    lv_obj_set_height(ui_Container_Lepton, lv_pct(100));
    lv_obj_set_align(ui_Container_Lepton, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container_Lepton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container_Lepton, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container_Lepton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Info_Container1 = lv_obj_create(ui_Container_Lepton);
    lv_obj_remove_style_all(ui_Info_Container1);
    lv_obj_set_width(ui_Info_Container1, lv_pct(50));
    lv_obj_set_height(ui_Info_Container1, lv_pct(100));
    lv_obj_set_align(ui_Info_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Info_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Info_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Info_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Info_Lepton_Serial_Name = lv_label_create(ui_Info_Container1);
    lv_obj_set_width(ui_Label_Info_Lepton_Serial_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Info_Lepton_Serial_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_Lepton_Serial_Name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Lepton_Serial_Name, "Serial:");
    lv_obj_remove_flag(ui_Label_Info_Lepton_Serial_Name,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Lepton_Serial_Name, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Lepton_Serial_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Lepton_Serial_Name, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_Lepton_Serial_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_Lepton_Serial_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_Lepton_Serial_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_Lepton_Serial_Name, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_Lepton_Part_Name = lv_label_create(ui_Info_Container1);
    lv_obj_set_width(ui_Label_Info_Lepton_Part_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Info_Lepton_Part_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_Lepton_Part_Name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Lepton_Part_Name, "Part Number:");
    lv_obj_remove_flag(ui_Label_Info_Lepton_Part_Name,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Lepton_Part_Name, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Lepton_Part_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Lepton_Part_Name, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_Lepton_Part_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_Lepton_Part_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_Lepton_Part_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_Lepton_Part_Name, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_Lepton_Revision_Name = lv_label_create(ui_Info_Container1);
    lv_obj_set_width(ui_Label_Info_Lepton_Revision_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Info_Lepton_Revision_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_Lepton_Revision_Name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Lepton_Revision_Name, "Software Revision:");
    lv_obj_remove_flag(ui_Label_Info_Lepton_Revision_Name,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Lepton_Revision_Name, lv_color_hex(0x888888),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Lepton_Revision_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Lepton_Revision_Name, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_Lepton_Revision_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_Lepton_Revision_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_Lepton_Revision_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_Lepton_Revision_Name, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_Lepton_Uptime_Name = lv_label_create(ui_Info_Container1);
    lv_obj_set_width(ui_Label_Info_Lepton_Uptime_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Info_Lepton_Uptime_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_Lepton_Uptime_Name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Lepton_Uptime_Name, "Uptime:");
    lv_obj_remove_flag(ui_Label_Info_Lepton_Uptime_Name,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Lepton_Uptime_Name, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Lepton_Uptime_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Lepton_Uptime_Name, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_Lepton_Uptime_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_Lepton_Uptime_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_Lepton_Uptime_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_Lepton_Uptime_Name, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_Lepton_FPA_Name = lv_label_create(ui_Info_Container1);
    lv_obj_set_width(ui_Label_Info_Lepton_FPA_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Info_Lepton_FPA_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Info_Lepton_FPA_Name, 0);
    lv_obj_set_y(ui_Label_Info_Lepton_FPA_Name, 1);
    lv_obj_set_align(ui_Label_Info_Lepton_FPA_Name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Lepton_FPA_Name, "FPA Temperature:");
    lv_obj_remove_flag(ui_Label_Info_Lepton_FPA_Name,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Lepton_FPA_Name, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Lepton_FPA_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Lepton_FPA_Name, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_Lepton_FPA_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_Lepton_FPA_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_Lepton_FPA_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_Lepton_FPA_Name, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_Lepton_AUX_Name = lv_label_create(ui_Info_Container1);
    lv_obj_set_width(ui_Label_Info_Lepton_AUX_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Info_Lepton_AUX_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_Lepton_AUX_Name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Lepton_AUX_Name, "AUX Temperature:");
    lv_obj_remove_flag(ui_Label_Info_Lepton_AUX_Name,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Lepton_AUX_Name, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Lepton_AUX_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Lepton_AUX_Name, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_Lepton_AUX_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_Lepton_AUX_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_Lepton_AUX_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_Lepton_AUX_Name, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info_Container7 = lv_obj_create(ui_Container_Lepton);
    lv_obj_remove_style_all(ui_Info_Container7);
    lv_obj_set_width(ui_Info_Container7, lv_pct(50));
    lv_obj_set_height(ui_Info_Container7, lv_pct(100));
    lv_obj_set_x(ui_Info_Container7, 172);
    lv_obj_set_y(ui_Info_Container7, -2);
    lv_obj_set_align(ui_Info_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Info_Container7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Info_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_Info_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Info_Lepton_Serial = lv_label_create(ui_Info_Container7);
    lv_obj_set_width(ui_Label_Info_Lepton_Serial, lv_pct(100));
    lv_obj_set_height(ui_Label_Info_Lepton_Serial, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_Lepton_Serial, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Lepton_Serial, "Nothing");
    lv_obj_remove_flag(ui_Label_Info_Lepton_Serial,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Lepton_Serial, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Lepton_Serial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Info_Lepton_Serial, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Lepton_Serial, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_Lepton_Serial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_Lepton_Serial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_Lepton_Serial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_Lepton_Serial, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_Lepton_Part = lv_label_create(ui_Info_Container7);
    lv_obj_set_width(ui_Label_Info_Lepton_Part, lv_pct(100));
    lv_obj_set_height(ui_Label_Info_Lepton_Part, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_Lepton_Part, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Lepton_Part, "Nothing");
    lv_obj_remove_flag(ui_Label_Info_Lepton_Part,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Lepton_Part, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Lepton_Part, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Info_Lepton_Part, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Lepton_Part, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_Lepton_Part, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_Lepton_Part, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_Lepton_Part, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_Lepton_Part, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_Lepton_Revision = lv_label_create(ui_Info_Container7);
    lv_obj_set_width(ui_Label_Info_Lepton_Revision, lv_pct(100));
    lv_obj_set_height(ui_Label_Info_Lepton_Revision, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_Lepton_Revision, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Lepton_Revision, "Nothing");
    lv_obj_remove_flag(ui_Label_Info_Lepton_Revision,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Lepton_Revision, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Lepton_Revision, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Info_Lepton_Revision, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Lepton_Revision, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_Lepton_Revision, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_Lepton_Revision, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_Lepton_Revision, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_Lepton_Revision, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_Lepton_Uptime = lv_label_create(ui_Info_Container7);
    lv_obj_set_width(ui_Label_Info_Lepton_Uptime, lv_pct(100));
    lv_obj_set_height(ui_Label_Info_Lepton_Uptime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_Lepton_Uptime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Lepton_Uptime, "0");
    lv_obj_remove_flag(ui_Label_Info_Lepton_Uptime,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Lepton_Uptime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Lepton_Uptime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Info_Lepton_Uptime, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Lepton_Uptime, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_Lepton_Uptime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_Lepton_Uptime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_Lepton_Uptime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_Lepton_Uptime, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_Lepton_FPA = lv_label_create(ui_Info_Container7);
    lv_obj_set_width(ui_Label_Info_Lepton_FPA, lv_pct(100));
    lv_obj_set_height(ui_Label_Info_Lepton_FPA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_Lepton_FPA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Lepton_FPA, "0");
    lv_obj_remove_flag(ui_Label_Info_Lepton_FPA,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Lepton_FPA, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Lepton_FPA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Info_Lepton_FPA, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Lepton_FPA, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_Lepton_FPA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_Lepton_FPA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_Lepton_FPA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_Lepton_FPA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Info_Lepton_AUX = lv_label_create(ui_Info_Container7);
    lv_obj_set_width(ui_Label_Info_Lepton_AUX, lv_pct(100));
    lv_obj_set_height(ui_Label_Info_Lepton_AUX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Info_Lepton_AUX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Info_Lepton_AUX, "0\n");
    lv_obj_remove_flag(ui_Label_Info_Lepton_AUX,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Info_Lepton_AUX, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Info_Lepton_AUX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Info_Lepton_AUX, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Info_Lepton_AUX, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Info_Lepton_AUX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Info_Lepton_AUX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Info_Lepton_AUX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Info_Lepton_AUX, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Info, ui_event_Info, LV_EVENT_ALL, NULL);

}

void ui_Info_screen_destroy(void)
{
    if(ui_Info) lv_obj_del(ui_Info);

    // NULL screen variables
    ui_Info = NULL;
    ui_Panel_Info_Header = NULL;
    ui_Label_Info_Header = NULL;
    ui_Panel_Info_Content = NULL;
    ui_Panel_Device = NULL;
    ui_Label_Info_Device = NULL;
    ui_Container_Info_Device = NULL;
    ui_Info_Container4 = NULL;
    ui_Label_Info_MAC_Name = NULL;
    ui_Label_Info_IP_Name = NULL;
    ui_Info_Container5 = NULL;
    ui_Label_Info_MAC = NULL;
    ui_Label_Info_IP = NULL;
    ui_Panel_Battery = NULL;
    ui_Label_Info_Battery = NULL;
    ui_Container_Battery = NULL;
    ui_Info_Container2 = NULL;
    ui_Label_Info_Battery_Status_Name = NULL;
    ui_Label_Info_Battery_Voltage_Name = NULL;
    ui_Label_Info_Battery_Remaining_Name = NULL;
    ui_Info_Container3 = NULL;
    ui_Label_Info_Battery_Status = NULL;
    ui_Label_Info_Battery_Voltage = NULL;
    ui_Label_Info_Battery_Remaining = NULL;
    ui_Info_Bar2 = NULL;
    ui_Panel_Lepton = NULL;
    ui_Label_Info_Lepton = NULL;
    ui_Container_Lepton = NULL;
    ui_Info_Container1 = NULL;
    ui_Label_Info_Lepton_Serial_Name = NULL;
    ui_Label_Info_Lepton_Part_Name = NULL;
    ui_Label_Info_Lepton_Revision_Name = NULL;
    ui_Label_Info_Lepton_Uptime_Name = NULL;
    ui_Label_Info_Lepton_FPA_Name = NULL;
    ui_Label_Info_Lepton_AUX_Name = NULL;
    ui_Info_Container7 = NULL;
    ui_Label_Info_Lepton_Serial = NULL;
    ui_Label_Info_Lepton_Part = NULL;
    ui_Label_Info_Lepton_Revision = NULL;
    ui_Label_Info_Lepton_Uptime = NULL;
    ui_Label_Info_Lepton_FPA = NULL;
    ui_Label_Info_Lepton_AUX = NULL;

}
