// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: PyroVision

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern void ui_event_Main(lv_event_t * e);
extern lv_obj_t *ui_Main;
extern lv_obj_t *ui_Container_Main_StatusBar;
extern lv_obj_t *ui_Image_Main_WiFi;
extern lv_obj_t *ui_Image_Main_SDCard;
extern lv_obj_t *ui_Label_Main_Time;
extern lv_obj_t *ui_Image_Main_Battery;
extern lv_obj_t *ui_Label_Main_Battery_Remaining;
extern lv_obj_t *ui_Container_Main_Thermal;
extern lv_obj_t *ui_Image_Thermal;
extern lv_obj_t *ui_Image_Main_Thermal_Scene_ROI;
extern lv_obj_t *ui_Image_Main_Thermal_Spotmeter_ROI;
extern lv_obj_t *ui_Image_Main_Thermal_Video_Focus_ROI;
extern lv_obj_t *ui_Image_Main_Thermal_AGC_ROI;
extern lv_obj_t *ui_Label_Main_Thermal_Crosshair;
extern lv_obj_t *ui_Label_Main_Thermal_PixelTemperature;
extern lv_obj_t *ui_Container_Main_Thermal_Scene_Statistics;
extern lv_obj_t *ui_Label_Main_Thermal_Scene_Max;
extern lv_obj_t *ui_Label_Main_Thermal_Scene_Min;
extern lv_obj_t *ui_Label_Main_Thermal_Scene_Mean;
extern lv_obj_t *ui_Container_Gradient;
extern lv_obj_t *ui_Label_TempScaleMax;
extern lv_obj_t *ui_Image_Gradient;
extern lv_obj_t *ui_Label_TempScaleMin;
extern lv_obj_t *ui_Container_Main_Buttons;
extern void ui_event_Button_Main_WiFi(lv_event_t * e);
extern lv_obj_t *ui_Button_Main_WiFi;
extern lv_obj_t *ui_Label_Main_Button_WiFi;
extern lv_obj_t *ui_Button_Main_ROI;
extern lv_obj_t *ui_Label_Main_Button_ROI;
extern void ui_event_Button_Main_Info(lv_event_t * e);
extern lv_obj_t *ui_Button_Main_Info;
extern lv_obj_t *ui_Label_Main_Button_Info;
extern void ui_event_Button_Main_Menu(lv_event_t * e);
extern lv_obj_t *ui_Button_Main_Menu;
extern lv_obj_t *ui_Label_Main_Button_Menu;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

