// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: PyroVision

#ifndef UI_MENU_H
#define UI_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Menu
extern void ui_Menu_screen_init(void);
extern void ui_Menu_screen_destroy(void);
extern void ui_event_Menu(lv_event_t * e);
extern lv_obj_t * ui_Menu;
extern lv_obj_t * ui_Panel_Menu_Header;
extern lv_obj_t * ui_Label_Menu_Header;
extern lv_obj_t * ui_Container_Menu;
extern lv_obj_t * ui_Container_Menu_Buttons;
extern void ui_event_Button_Menu_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button_Menu_Button1;
extern lv_obj_t * ui_Label_Menu_Button1;
extern void ui_event_Button_Menu_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button_Menu_Button4;
extern lv_obj_t * ui_Label_Menu_Button4;
extern void ui_event_Button_Menu_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button_Menu_Button3;
extern lv_obj_t * ui_Label_Info_Button3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

