// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: PyroVision

#include "../ui.h"

lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_Container_Main_Statusbar = NULL;
lv_obj_t * ui_Image_Main_WiFi = NULL;
lv_obj_t * ui_Image_Main_SDCard = NULL;
lv_obj_t * ui_Label_Main_Time = NULL;
lv_obj_t * ui_Container_Main_Statusbar_Temperature = NULL;
lv_obj_t * ui_Label_Main_Statusbar_Temperatur_Icon = NULL;
lv_obj_t * ui_Label_Main_Statusbar_Temperatur = NULL;
lv_obj_t * ui_Container_Main_Statusbar_Battery = NULL;
lv_obj_t * ui_Label_Main_Battery_Remaining_Icon = NULL;
lv_obj_t * ui_Label_Main_Battery_Remaining = NULL;
lv_obj_t * ui_Container_Main_Thermal = NULL;
lv_obj_t * ui_Image_Main_Image = NULL;
lv_obj_t * ui_Label_Main_Distance = NULL;
lv_obj_t * ui_Image_Main_Thermal_Scene_ROI = NULL;
lv_obj_t * ui_Image_Main_Thermal_Spotmeter_ROI = NULL;
lv_obj_t * ui_Image_Main_Thermal_Video_Focus_ROI = NULL;
lv_obj_t * ui_Image_Main_Thermal_AGC_ROI = NULL;
lv_obj_t * ui_Container_Main_Thermal_Scene_Statistics = NULL;
lv_obj_t * ui_Label_Main_Thermal_Scene_Max = NULL;
lv_obj_t * ui_Label_Main_Thermal_Scene_Min = NULL;
lv_obj_t * ui_Label_Main_Thermal_Scene_Mean = NULL;
lv_obj_t * ui_Container_Main_Thermal_Crosshair = NULL;
lv_obj_t * ui_Label_Main_Thermal_Pixel_Temperature = NULL;
lv_obj_t * ui_Label_Main_Thermal_Crosshair = NULL;
lv_obj_t * ui_Container_Main_Gradient = NULL;
lv_obj_t * ui_Label_Main_TempScaleMax = NULL;
lv_obj_t * ui_Image_Main_Gradient = NULL;
lv_obj_t * ui_Label_Main_TempScaleMin = NULL;
lv_obj_t * ui_Container_Main_Buttons = NULL;
lv_obj_t * ui_Button_Main_Save = NULL;
lv_obj_t * ui_Label_Main_Button_Save = NULL;
lv_obj_t * ui_Button_Main_ROI = NULL;
lv_obj_t * ui_Label_Main_Button_ROI = NULL;
lv_obj_t * ui_Button_Main_Switch = NULL;
lv_obj_t * ui_Label_Main_Button_Switch = NULL;
lv_obj_t * ui_Button_Main_Menu = NULL;
lv_obj_t * ui_Label_Main_Button_Menu = NULL;
// event funtions
void ui_event_Main(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ScreenMainLoaded(e);
    }
}

void ui_event_Button_Main_Save(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ButtonMainSaveClicked(e);
    }
}

void ui_event_Button_Main_ROI(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ButtonMainROIClicked(e);
    }
}

void ui_event_Button_Main_Switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ButtonMainSwitchClicked(e);
    }
}

void ui_event_Button_Main_Menu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Menu_screen_init);
    }
}

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Main, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Main, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_Main_Statusbar = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_Container_Main_Statusbar);
    lv_obj_set_width(ui_Container_Main_Statusbar, 320);
    lv_obj_set_height(ui_Container_Main_Statusbar, lv_pct(8));
    lv_obj_set_align(ui_Container_Main_Statusbar, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container_Main_Statusbar,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Container_Main_Statusbar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container_Main_Statusbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Container_Main_Statusbar, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_Main_WiFi = lv_label_create(ui_Container_Main_Statusbar);
    lv_obj_set_height(ui_Image_Main_WiFi, lv_pct(100));
    lv_obj_set_width(ui_Image_Main_WiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Image_Main_WiFi, 5);
    lv_obj_set_y(ui_Image_Main_WiFi, 0);
    lv_label_set_text(ui_Image_Main_WiFi, "W");
    lv_obj_remove_flag(ui_Image_Main_WiFi,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Image_Main_WiFi, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Image_Main_WiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Image_Main_WiFi, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_Main_SDCard = lv_label_create(ui_Container_Main_Statusbar);
    lv_obj_set_height(ui_Image_Main_SDCard, lv_pct(100));
    lv_obj_set_width(ui_Image_Main_SDCard, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Image_Main_SDCard, 25);
    lv_obj_set_y(ui_Image_Main_SDCard, 0);
    lv_label_set_text(ui_Image_Main_SDCard, "C");
    lv_obj_remove_flag(ui_Image_Main_SDCard,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Image_Main_SDCard, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Image_Main_SDCard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Image_Main_SDCard, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Main_Time = lv_label_create(ui_Container_Main_Statusbar);
    lv_obj_set_height(ui_Label_Main_Time, lv_pct(100));
    lv_obj_set_width(ui_Label_Main_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label_Main_Time, -50);
    lv_obj_set_y(ui_Label_Main_Time, 0);
    lv_obj_set_align(ui_Label_Main_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Main_Time, "12:34:56");
    lv_obj_remove_flag(ui_Label_Main_Time,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Main_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Main_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Main_Time, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_Main_Statusbar_Temperature = lv_obj_create(ui_Container_Main_Statusbar);
    lv_obj_remove_style_all(ui_Container_Main_Statusbar_Temperature);
    lv_obj_set_height(ui_Container_Main_Statusbar_Temperature, lv_pct(100));
    lv_obj_set_width(ui_Container_Main_Statusbar_Temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Container_Main_Statusbar_Temperature, 40);
    lv_obj_set_y(ui_Container_Main_Statusbar_Temperature, 0);
    lv_obj_set_align(ui_Container_Main_Statusbar_Temperature, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container_Main_Statusbar_Temperature, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container_Main_Statusbar_Temperature, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container_Main_Statusbar_Temperature,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Main_Statusbar_Temperatur_Icon = lv_label_create(ui_Container_Main_Statusbar_Temperature);
    lv_obj_set_width(ui_Label_Main_Statusbar_Temperatur_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Main_Statusbar_Temperatur_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Main_Statusbar_Temperatur_Icon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Main_Statusbar_Temperatur_Icon, "I");
    lv_obj_set_style_text_color(ui_Label_Main_Statusbar_Temperatur_Icon, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Main_Statusbar_Temperatur_Icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Main_Statusbar_Temperatur_Icon, &ui_font_fa12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Main_Statusbar_Temperatur_Icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Main_Statusbar_Temperatur_Icon, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Main_Statusbar_Temperatur_Icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Main_Statusbar_Temperatur_Icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Main_Statusbar_Temperatur = lv_label_create(ui_Container_Main_Statusbar_Temperature);
    lv_obj_set_width(ui_Label_Main_Statusbar_Temperatur, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Main_Statusbar_Temperatur, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Main_Statusbar_Temperatur, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Main_Statusbar_Temperatur, "0 °C");
    lv_obj_set_style_text_color(ui_Label_Main_Statusbar_Temperatur, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Main_Statusbar_Temperatur, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Main_Statusbar_Temperatur, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_Main_Statusbar_Battery = lv_obj_create(ui_Container_Main_Statusbar);
    lv_obj_remove_style_all(ui_Container_Main_Statusbar_Battery);
    lv_obj_set_height(ui_Container_Main_Statusbar_Battery, lv_pct(100));
    lv_obj_set_width(ui_Container_Main_Statusbar_Battery, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_x(ui_Container_Main_Statusbar_Battery, 110);
    lv_obj_set_y(ui_Container_Main_Statusbar_Battery, 0);
    lv_obj_set_align(ui_Container_Main_Statusbar_Battery, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container_Main_Statusbar_Battery, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container_Main_Statusbar_Battery, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container_Main_Statusbar_Battery, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_pad_left(ui_Container_Main_Statusbar_Battery, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container_Main_Statusbar_Battery, 50, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container_Main_Statusbar_Battery, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container_Main_Statusbar_Battery, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label_Main_Battery_Remaining_Icon = lv_label_create(ui_Container_Main_Statusbar_Battery);
    lv_obj_set_width(ui_Label_Main_Battery_Remaining_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Main_Battery_Remaining_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Main_Battery_Remaining_Icon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Main_Battery_Remaining_Icon, "B");
    lv_obj_set_style_text_color(ui_Label_Main_Battery_Remaining_Icon, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Main_Battery_Remaining_Icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Main_Battery_Remaining_Icon, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Main_Battery_Remaining_Icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Main_Battery_Remaining_Icon, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Main_Battery_Remaining_Icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Main_Battery_Remaining_Icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Main_Battery_Remaining = lv_label_create(ui_Container_Main_Statusbar_Battery);
    lv_obj_set_width(ui_Label_Main_Battery_Remaining, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Main_Battery_Remaining, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Main_Battery_Remaining, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Main_Battery_Remaining, "100%");
    lv_obj_set_style_text_color(ui_Label_Main_Battery_Remaining, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Main_Battery_Remaining, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Main_Battery_Remaining, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_Main_Thermal = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_Container_Main_Thermal);
    lv_obj_set_width(ui_Container_Main_Thermal, lv_pct(100));
    lv_obj_set_height(ui_Container_Main_Thermal, lv_pct(75));
    lv_obj_set_x(ui_Container_Main_Thermal, 0);
    lv_obj_set_y(ui_Container_Main_Thermal, 10);
    lv_obj_set_align(ui_Container_Main_Thermal, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container_Main_Thermal, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Main_Image = lv_image_create(ui_Container_Main_Thermal);
    lv_obj_set_width(ui_Image_Main_Image, 240);
    lv_obj_set_height(ui_Image_Main_Image, 180);
    lv_obj_set_x(ui_Image_Main_Image, 10);
    lv_obj_set_y(ui_Image_Main_Image, 0);
    lv_obj_set_align(ui_Image_Main_Image, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image_Main_Image,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_image_set_rotation(ui_Image_Main_Image, 1800);
    lv_obj_set_style_radius(ui_Image_Main_Image, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Image_Main_Image, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image_Main_Image, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Image_Main_Image, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Main_Distance = lv_label_create(ui_Image_Main_Image);
    lv_obj_set_width(ui_Label_Main_Distance, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Main_Distance, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Main_Distance, 10);
    lv_obj_set_y(ui_Label_Main_Distance, 10);
    lv_label_set_text(ui_Label_Main_Distance, "0 cm");
    lv_obj_set_style_text_color(ui_Label_Main_Distance, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Main_Distance, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Main_Distance, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_Main_Thermal_Scene_ROI = lv_obj_create(ui_Image_Main_Image);
    lv_obj_set_width(ui_Image_Main_Thermal_Scene_ROI, 240);
    lv_obj_set_height(ui_Image_Main_Thermal_Scene_ROI, 180);
    lv_obj_set_align(ui_Image_Main_Thermal_Scene_ROI, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Main_Thermal_Scene_ROI, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Image_Main_Thermal_Scene_ROI,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Image_Main_Thermal_Scene_ROI, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Image_Main_Thermal_Scene_ROI, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image_Main_Thermal_Scene_ROI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Image_Main_Thermal_Scene_ROI, lv_color_hex(0xF03FEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Image_Main_Thermal_Scene_ROI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Image_Main_Thermal_Scene_ROI, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_Main_Thermal_Spotmeter_ROI = lv_obj_create(ui_Image_Main_Image);
    lv_obj_set_width(ui_Image_Main_Thermal_Spotmeter_ROI, 2);
    lv_obj_set_height(ui_Image_Main_Thermal_Spotmeter_ROI, 2);
    lv_obj_set_x(ui_Image_Main_Thermal_Spotmeter_ROI, -1);
    lv_obj_set_y(ui_Image_Main_Thermal_Spotmeter_ROI, -1);
    lv_obj_set_align(ui_Image_Main_Thermal_Spotmeter_ROI, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Main_Thermal_Spotmeter_ROI, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Image_Main_Thermal_Spotmeter_ROI,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Image_Main_Thermal_Spotmeter_ROI, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Image_Main_Thermal_Spotmeter_ROI, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image_Main_Thermal_Spotmeter_ROI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Image_Main_Thermal_Spotmeter_ROI, lv_color_hex(0x7B3FF0),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Image_Main_Thermal_Spotmeter_ROI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Image_Main_Thermal_Spotmeter_ROI, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_Main_Thermal_Video_Focus_ROI = lv_obj_create(ui_Image_Main_Image);
    lv_obj_set_width(ui_Image_Main_Thermal_Video_Focus_ROI, 238);
    lv_obj_set_height(ui_Image_Main_Thermal_Video_Focus_ROI, 178);
    lv_obj_set_align(ui_Image_Main_Thermal_Video_Focus_ROI, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Main_Thermal_Video_Focus_ROI, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Image_Main_Thermal_Video_Focus_ROI,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Image_Main_Thermal_Video_Focus_ROI, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Image_Main_Thermal_Video_Focus_ROI, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image_Main_Thermal_Video_Focus_ROI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Image_Main_Thermal_Video_Focus_ROI, lv_color_hex(0xEBF03F),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Image_Main_Thermal_Video_Focus_ROI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Image_Main_Thermal_Video_Focus_ROI, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_Main_Thermal_AGC_ROI = lv_obj_create(ui_Image_Main_Image);
    lv_obj_set_width(ui_Image_Main_Thermal_AGC_ROI, 240);
    lv_obj_set_height(ui_Image_Main_Thermal_AGC_ROI, 180);
    lv_obj_set_align(ui_Image_Main_Thermal_AGC_ROI, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Main_Thermal_AGC_ROI, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Image_Main_Thermal_AGC_ROI,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Image_Main_Thermal_AGC_ROI, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Image_Main_Thermal_AGC_ROI, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image_Main_Thermal_AGC_ROI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Image_Main_Thermal_AGC_ROI, lv_color_hex(0x3F96F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Image_Main_Thermal_AGC_ROI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Image_Main_Thermal_AGC_ROI, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_Main_Thermal_Scene_Statistics = lv_obj_create(ui_Image_Main_Image);
    lv_obj_remove_style_all(ui_Container_Main_Thermal_Scene_Statistics);
    lv_obj_set_height(ui_Container_Main_Thermal_Scene_Statistics, 20);
    lv_obj_set_width(ui_Container_Main_Thermal_Scene_Statistics, lv_pct(100));
    lv_obj_set_x(ui_Container_Main_Thermal_Scene_Statistics, 0);
    lv_obj_set_y(ui_Container_Main_Thermal_Scene_Statistics, -5);
    lv_obj_set_align(ui_Container_Main_Thermal_Scene_Statistics, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Container_Main_Thermal_Scene_Statistics,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Main_Thermal_Scene_Max = lv_label_create(ui_Container_Main_Thermal_Scene_Statistics);
    lv_obj_set_width(ui_Label_Main_Thermal_Scene_Max, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Main_Thermal_Scene_Max, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Main_Thermal_Scene_Max, 10);
    lv_obj_set_y(ui_Label_Main_Thermal_Scene_Max, 0);
    lv_obj_set_align(ui_Label_Main_Thermal_Scene_Max, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Main_Thermal_Scene_Max, "100.0");
    lv_obj_set_style_text_color(ui_Label_Main_Thermal_Scene_Max, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Main_Thermal_Scene_Max, 192, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Main_Thermal_Scene_Max, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Label_Main_Thermal_Scene_Max, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label_Main_Thermal_Scene_Max, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label_Main_Thermal_Scene_Max, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label_Main_Thermal_Scene_Max, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label_Main_Thermal_Scene_Max, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Main_Thermal_Scene_Min = lv_label_create(ui_Container_Main_Thermal_Scene_Statistics);
    lv_obj_set_width(ui_Label_Main_Thermal_Scene_Min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Main_Thermal_Scene_Min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Main_Thermal_Scene_Min, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Main_Thermal_Scene_Min, "-40.0");
    lv_obj_set_style_text_color(ui_Label_Main_Thermal_Scene_Min, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Main_Thermal_Scene_Min, 192, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Main_Thermal_Scene_Min, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Label_Main_Thermal_Scene_Min, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Main_Thermal_Scene_Mean = lv_label_create(ui_Container_Main_Thermal_Scene_Statistics);
    lv_obj_set_width(ui_Label_Main_Thermal_Scene_Mean, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Main_Thermal_Scene_Mean, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Main_Thermal_Scene_Mean, -10);
    lv_obj_set_y(ui_Label_Main_Thermal_Scene_Mean, 0);
    lv_obj_set_align(ui_Label_Main_Thermal_Scene_Mean, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Main_Thermal_Scene_Mean, "80.0");
    lv_obj_set_style_text_color(ui_Label_Main_Thermal_Scene_Mean, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Main_Thermal_Scene_Mean, 192, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Main_Thermal_Scene_Mean, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Label_Main_Thermal_Scene_Mean, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_Main_Thermal_Crosshair = lv_obj_create(ui_Image_Main_Image);
    lv_obj_remove_style_all(ui_Container_Main_Thermal_Crosshair);
    lv_obj_set_width(ui_Container_Main_Thermal_Crosshair, 100);
    lv_obj_set_height(ui_Container_Main_Thermal_Crosshair, 50);
    lv_obj_set_align(ui_Container_Main_Thermal_Crosshair, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container_Main_Thermal_Crosshair,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_Label_Main_Thermal_Pixel_Temperature = lv_label_create(ui_Container_Main_Thermal_Crosshair);
    lv_obj_set_width(ui_Label_Main_Thermal_Pixel_Temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Main_Thermal_Pixel_Temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Main_Thermal_Pixel_Temperature, 0);
    lv_obj_set_y(ui_Label_Main_Thermal_Pixel_Temperature, -15);
    lv_obj_set_align(ui_Label_Main_Thermal_Pixel_Temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Main_Thermal_Pixel_Temperature, "101.1");
    lv_obj_remove_flag(ui_Label_Main_Thermal_Pixel_Temperature,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Main_Thermal_Pixel_Temperature, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Main_Thermal_Pixel_Temperature, 192, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Main_Thermal_Pixel_Temperature, &lv_font_montserrat_14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Main_Thermal_Crosshair = lv_label_create(ui_Container_Main_Thermal_Crosshair);
    lv_obj_set_width(ui_Label_Main_Thermal_Crosshair, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Main_Thermal_Crosshair, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Main_Thermal_Crosshair, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Main_Thermal_Crosshair, "CH");
    lv_obj_remove_flag(ui_Label_Main_Thermal_Crosshair,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_font(ui_Label_Main_Thermal_Crosshair, &ui_font_fa16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_Main_Gradient = lv_obj_create(ui_Container_Main_Thermal);
    lv_obj_remove_style_all(ui_Container_Main_Gradient);
    lv_obj_set_width(ui_Container_Main_Gradient, 40);
    lv_obj_set_height(ui_Container_Main_Gradient, 190);
    lv_obj_set_x(ui_Container_Main_Gradient, -135);
    lv_obj_set_y(ui_Container_Main_Gradient, 0);
    lv_obj_set_align(ui_Container_Main_Gradient, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container_Main_Gradient, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Main_TempScaleMax = lv_label_create(ui_Container_Main_Gradient);
    lv_obj_set_height(ui_Label_Main_TempScaleMax, 20);
    lv_obj_set_width(ui_Label_Main_TempScaleMax, lv_pct(100));
    lv_obj_set_x(ui_Label_Main_TempScaleMax, 0);
    lv_obj_set_y(ui_Label_Main_TempScaleMax, -80);
    lv_obj_set_align(ui_Label_Main_TempScaleMax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Main_TempScaleMax, "Max");
    lv_obj_set_style_text_color(ui_Label_Main_TempScaleMax, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Main_TempScaleMax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Main_TempScaleMax, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label_Main_TempScaleMax, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Main_TempScaleMax, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_Main_Gradient = lv_image_create(ui_Container_Main_Gradient);
    lv_obj_set_height(ui_Image_Main_Gradient, 150);
    lv_obj_set_width(ui_Image_Main_Gradient, lv_pct(50));
    lv_obj_set_align(ui_Image_Main_Gradient, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Main_Gradient, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image_Main_Gradient, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Image_Main_Gradient, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Image_Main_Gradient, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image_Main_Gradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Image_Main_Gradient, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Image_Main_Gradient, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Main_TempScaleMin = lv_label_create(ui_Container_Main_Gradient);
    lv_obj_set_height(ui_Label_Main_TempScaleMin, 20);
    lv_obj_set_width(ui_Label_Main_TempScaleMin, lv_pct(100));
    lv_obj_set_x(ui_Label_Main_TempScaleMin, 0);
    lv_obj_set_y(ui_Label_Main_TempScaleMin, 90);
    lv_obj_set_align(ui_Label_Main_TempScaleMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Main_TempScaleMin, "Min");
    lv_obj_set_style_text_color(ui_Label_Main_TempScaleMin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Main_TempScaleMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Main_TempScaleMin, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Main_TempScaleMin, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_Main_Buttons = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_Container_Main_Buttons);
    lv_obj_set_width(ui_Container_Main_Buttons, lv_pct(100));
    lv_obj_set_height(ui_Container_Main_Buttons, lv_pct(10));
    lv_obj_set_x(ui_Container_Main_Buttons, 108);
    lv_obj_set_y(ui_Container_Main_Buttons, -14);
    lv_obj_set_align(ui_Container_Main_Buttons, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container_Main_Buttons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button_Main_Save = lv_button_create(ui_Container_Main_Buttons);
    lv_obj_set_width(ui_Button_Main_Save, 50);
    lv_obj_set_height(ui_Button_Main_Save, lv_pct(95));
    lv_obj_set_x(ui_Button_Main_Save, 130);
    lv_obj_set_y(ui_Button_Main_Save, 0);
    lv_obj_set_align(ui_Button_Main_Save, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Button_Main_Save,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Button_Main_Save, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Main_Save, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button_Main_Save, lv_color_hex(0xB998FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button_Main_Save, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button_Main_Save, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Main_Button_Save = lv_label_create(ui_Button_Main_Save);
    lv_obj_set_width(ui_Label_Main_Button_Save, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Main_Button_Save, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Main_Button_Save, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Main_Button_Save, "S");
    lv_obj_set_style_text_color(ui_Label_Main_Button_Save, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Main_Button_Save, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Main_Button_Save, &ui_font_fa16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Main_ROI = lv_button_create(ui_Container_Main_Buttons);
    lv_obj_set_width(ui_Button_Main_ROI, 50);
    lv_obj_set_height(ui_Button_Main_ROI, lv_pct(95));
    lv_obj_set_x(ui_Button_Main_ROI, -45);
    lv_obj_set_y(ui_Button_Main_ROI, 0);
    lv_obj_set_align(ui_Button_Main_ROI, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Button_Main_ROI,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Button_Main_ROI, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Main_ROI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button_Main_ROI, lv_color_hex(0xB998FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button_Main_ROI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button_Main_ROI, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Main_Button_ROI = lv_label_create(ui_Button_Main_ROI);
    lv_obj_set_width(ui_Label_Main_Button_ROI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Main_Button_ROI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Main_Button_ROI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Main_Button_ROI, "R");
    lv_obj_set_style_text_color(ui_Label_Main_Button_ROI, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Main_Button_ROI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Main_Button_ROI, &ui_font_fa16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Main_Switch = lv_button_create(ui_Container_Main_Buttons);
    lv_obj_set_width(ui_Button_Main_Switch, 50);
    lv_obj_set_height(ui_Button_Main_Switch, lv_pct(95));
    lv_obj_set_x(ui_Button_Main_Switch, 45);
    lv_obj_set_y(ui_Button_Main_Switch, 0);
    lv_obj_set_align(ui_Button_Main_Switch, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Button_Main_Switch,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Button_Main_Switch, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Main_Switch, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button_Main_Switch, lv_color_hex(0xB998FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button_Main_Switch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button_Main_Switch, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Main_Button_Switch = lv_label_create(ui_Button_Main_Switch);
    lv_obj_set_width(ui_Label_Main_Button_Switch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Main_Button_Switch, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Main_Button_Switch, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Main_Button_Switch, "I");
    lv_obj_set_style_text_font(ui_Label_Main_Button_Switch, &ui_font_fa16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Main_Menu = lv_button_create(ui_Container_Main_Buttons);
    lv_obj_set_width(ui_Button_Main_Menu, 50);
    lv_obj_set_height(ui_Button_Main_Menu, lv_pct(95));
    lv_obj_set_x(ui_Button_Main_Menu, -130);
    lv_obj_set_y(ui_Button_Main_Menu, 0);
    lv_obj_set_align(ui_Button_Main_Menu, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Button_Main_Menu,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Button_Main_Menu, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Main_Menu, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button_Main_Menu, lv_color_hex(0xB998FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button_Main_Menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button_Main_Menu, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Main_Button_Menu = lv_label_create(ui_Button_Main_Menu);
    lv_obj_set_width(ui_Label_Main_Button_Menu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Main_Button_Menu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Main_Button_Menu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Main_Button_Menu, "M");
    lv_obj_set_style_text_font(ui_Label_Main_Button_Menu, &ui_font_fa16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button_Main_Save, ui_event_Button_Main_Save, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Main_ROI, ui_event_Button_Main_ROI, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Main_Switch, ui_event_Button_Main_Switch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Main_Menu, ui_event_Button_Main_Menu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main, ui_event_Main, LV_EVENT_ALL, NULL);

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_Container_Main_Statusbar = NULL;
    ui_Image_Main_WiFi = NULL;
    ui_Image_Main_SDCard = NULL;
    ui_Label_Main_Time = NULL;
    ui_Container_Main_Statusbar_Temperature = NULL;
    ui_Label_Main_Statusbar_Temperatur_Icon = NULL;
    ui_Label_Main_Statusbar_Temperatur = NULL;
    ui_Container_Main_Statusbar_Battery = NULL;
    ui_Label_Main_Battery_Remaining_Icon = NULL;
    ui_Label_Main_Battery_Remaining = NULL;
    ui_Container_Main_Thermal = NULL;
    ui_Image_Main_Image = NULL;
    ui_Label_Main_Distance = NULL;
    ui_Image_Main_Thermal_Scene_ROI = NULL;
    ui_Image_Main_Thermal_Spotmeter_ROI = NULL;
    ui_Image_Main_Thermal_Video_Focus_ROI = NULL;
    ui_Image_Main_Thermal_AGC_ROI = NULL;
    ui_Container_Main_Thermal_Scene_Statistics = NULL;
    ui_Label_Main_Thermal_Scene_Max = NULL;
    ui_Label_Main_Thermal_Scene_Min = NULL;
    ui_Label_Main_Thermal_Scene_Mean = NULL;
    ui_Container_Main_Thermal_Crosshair = NULL;
    ui_Label_Main_Thermal_Pixel_Temperature = NULL;
    ui_Label_Main_Thermal_Crosshair = NULL;
    ui_Container_Main_Gradient = NULL;
    ui_Label_Main_TempScaleMax = NULL;
    ui_Image_Main_Gradient = NULL;
    ui_Label_Main_TempScaleMin = NULL;
    ui_Container_Main_Buttons = NULL;
    ui_Button_Main_Save = NULL;
    ui_Label_Main_Button_Save = NULL;
    ui_Button_Main_ROI = NULL;
    ui_Label_Main_Button_ROI = NULL;
    ui_Button_Main_Switch = NULL;
    ui_Label_Main_Button_Switch = NULL;
    ui_Button_Main_Menu = NULL;
    ui_Label_Main_Button_Menu = NULL;

}
