// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: PyroVision

#include "../ui.h"

lv_obj_t * ui_Menu = NULL;
lv_obj_t * ui_Panel_Menu_Header = NULL;
lv_obj_t * ui_Label_Menu_Header = NULL;
lv_obj_t * ui_Container_Menu = NULL;
// event funtions
void ui_event_Menu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Main_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ScreenMenuLoaded(e);
    }
}

// build funtions

void ui_Menu_screen_init(void)
{
    ui_Menu = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Menu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Menu, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Menu_Header = lv_obj_create(ui_Menu);
    lv_obj_set_width(ui_Panel_Menu_Header, 320);
    lv_obj_set_height(ui_Panel_Menu_Header, lv_pct(12));
    lv_obj_set_x(ui_Panel_Menu_Header, 1);
    lv_obj_set_y(ui_Panel_Menu_Header, 1);
    lv_obj_set_align(ui_Panel_Menu_Header, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Panel_Menu_Header,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Panel_Menu_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_Menu_Header, lv_color_hex(0x7B3FF0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Menu_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_Menu_Header, lv_color_hex(0x7B3FF0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_Menu_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Menu_Header = lv_label_create(ui_Panel_Menu_Header);
    lv_obj_set_width(ui_Label_Menu_Header, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Menu_Header, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Menu_Header, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Menu_Header, "MENU");
    lv_obj_remove_flag(ui_Label_Menu_Header,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label_Menu_Header, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Menu_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Menu_Header, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_Menu = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_Container_Menu);
    lv_obj_set_height(ui_Container_Menu, 210);
    lv_obj_set_width(ui_Container_Menu, lv_pct(100));
    lv_obj_set_x(ui_Container_Menu, 0);
    lv_obj_set_y(ui_Container_Menu, 15);
    lv_obj_set_align(ui_Container_Menu, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container_Menu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Menu, ui_event_Menu, LV_EVENT_ALL, NULL);

}

void ui_Menu_screen_destroy(void)
{
    if(ui_Menu) lv_obj_del(ui_Menu);

    // NULL screen variables
    ui_Menu = NULL;
    ui_Panel_Menu_Header = NULL;
    ui_Label_Menu_Header = NULL;
    ui_Container_Menu = NULL;

}
