// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: PyroVision

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern void ui_event_Main(lv_event_t * e);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Container_Main_Statusbar;
extern lv_obj_t * ui_Image_Main_WiFi;
extern lv_obj_t * ui_Image_Main_SDCard;
extern lv_obj_t * ui_Label_Main_Time;
extern lv_obj_t * ui_Container_Main_Statusbar_Temperature;
extern lv_obj_t * ui_Label_Main_Statusbar_Temperatur_Icon;
extern lv_obj_t * ui_Label_Main_Statusbar_Temperatur;
extern lv_obj_t * ui_Container_Main_Statusbar_Battery;
extern lv_obj_t * ui_Label_Main_Battery_Remaining_Icon;
extern lv_obj_t * ui_Label_Main_Battery_Remaining;
extern lv_obj_t * ui_Container_Main_Thermal;
extern lv_obj_t * ui_Image_Main_Image;
extern lv_obj_t * ui_Label_Main_Distance;
extern lv_obj_t * ui_Image_Main_Thermal_Scene_ROI;
extern lv_obj_t * ui_Image_Main_Thermal_Spotmeter_ROI;
extern lv_obj_t * ui_Image_Main_Thermal_Video_Focus_ROI;
extern lv_obj_t * ui_Image_Main_Thermal_AGC_ROI;
extern lv_obj_t * ui_Container_Main_Thermal_Scene_Statistics;
extern lv_obj_t * ui_Label_Main_Thermal_Scene_Max;
extern lv_obj_t * ui_Label_Main_Thermal_Scene_Min;
extern lv_obj_t * ui_Label_Main_Thermal_Scene_Mean;
extern lv_obj_t * ui_Container_Main_Thermal_Crosshair;
extern lv_obj_t * ui_Label_Main_Thermal_Pixel_Temperature;
extern lv_obj_t * ui_Label_Main_Thermal_Crosshair;
extern lv_obj_t * ui_Container_Main_Gradient;
extern lv_obj_t * ui_Label_Main_Temp_Scale_Max;
extern lv_obj_t * ui_Image_Main_Gradient;
extern lv_obj_t * ui_Label_Main_Temp_Scale_Min;
extern lv_obj_t * ui_Label_Main_ROI_Name;
extern lv_obj_t * ui_Container_Main_Buttons;
extern void ui_event_Button_Main_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button_Main_Button4;
extern lv_obj_t * ui_Label_Main_Button4;
extern void ui_event_Button_Main_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button_Main_Button2;
extern lv_obj_t * ui_Label_Main_Button2;
extern void ui_event_Button_Main_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button_Main_Button3;
extern lv_obj_t * ui_Label_Main_Button3;
extern void ui_event_Button_Main_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button_Main_Button1;
extern lv_obj_t * ui_Label_Main_Button1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

