// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: PyroVision

#ifndef UI_SPLASH_H
#define UI_SPLASH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Splash
extern void ui_Splash_screen_init(void);
extern void ui_Splash_screen_destroy(void);
extern void ui_event_Splash(lv_event_t * e);
extern lv_obj_t * ui_Splash;
extern lv_obj_t * ui_Image_Splash_Logo;
extern lv_obj_t * ui_Image_Splash_Name;
extern lv_obj_t * ui_Label_Splash_Slogan;
extern lv_obj_t * ui_ProgressBar_Splash_Loading;
extern lv_obj_t * ui_Label_Splash_StatusText;
extern lv_obj_t * ui_Label_Splash_FirmwareVersion;
extern lv_obj_t * ui_Label_Splash_Copyright;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

