// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: PyroVision

#ifndef UI_SPLASH_H
#define UI_SPLASH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Splash
extern void ui_Splash_screen_init(void);
extern void ui_Splash_screen_destroy(void);
extern lv_obj_t *ui_Splash;
extern lv_obj_t *ui_SplashScreen_Logo;
extern lv_obj_t *ui_SplashScreen_LogoText;
extern lv_obj_t *ui_SplashScreen_Subtext;
extern lv_obj_t *ui_SplashScreen_LoadingBar;
extern lv_obj_t *ui_SplashScreen_StatusText;
extern lv_obj_t *ui_SplashScreen_FirmwareVersion;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

