// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: PyroVision

#ifndef _PYROVISION_UI_H
#define _PYROVISION_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Splash.h"
#include "screens/ui_Main.h"
#include "screens/ui_Menu.h"
#include "screens/ui_Info.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo_80x44_png);    // assets/Logo_80x44.png
LV_IMG_DECLARE(ui_img_text_218x40_png);    // assets/Text_218x40.png

// FONTS
LV_FONT_DECLARE(ui_font_fa);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
