// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: PyroVision

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

/** @brief          Callback for the message box timer to close the box after a delay.
 *  @param p_Timer  Timer handle (user data is the message box to close)
 */
void MessageBox_on_Close(lv_timer_t *p_Timer);

void ScreenSplashLoaded(lv_event_t *e);
void ScreenMainLoaded(lv_event_t *e);
void ButtonMainSaveClicked(lv_event_t *e);
void ButtonMenuSaveClicked(lv_event_t *e);
void ScreenInfoLoaded(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
