// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: PyroVision

#include <esp_log.h>
#include <esp_event.h>

#include "ui.h"

#include "../UI/ui_Settings.h"
#include "../../../application.h"

/** @brief          Callback for the message box timer to close the box after a delay.
 *  @param p_Timer  Timer handle (user data is the message box to close)
 */
static void MessageBox_on_Close(lv_timer_t * p_Timer)
{
    lv_obj_t * Box = (lv_obj_t *)lv_timer_get_user_data(p_Timer);
    lv_msgbox_close(Box);
}

void ScreenMainLoaded(lv_event_t *e)
{
    char Buf[128];
    App_Settings_Info_t Info;

    SettingsManager_GetInfo(&Info);

    snprintf(Buf, sizeof(Buf), "Firmware %s\n(c) 2026 PyroVision Project", Info.FirmwareVersion);
    lv_label_set_text(ui_SplashScreen_FirmwareVersion, Buf);

    /* Set the symbols for the UI */
    lv_label_set_text(ui_Image_Main_WiFi, LV_SYMBOL_WIFI);
    lv_label_set_text(ui_Image_Main_SDCard, LV_SYMBOL_SD_CARD);
    lv_label_set_text(ui_Label_Menu_Button_Save, LV_SYMBOL_SAVE);
    lv_label_set_text(ui_Label_Main_Button_Menu, "\uF0C9");
    lv_label_set_text(ui_Label_Main_Button_Info, "\uF129");
    lv_label_set_text(ui_Label_Main_Button_ROI, "\uE595");
    lv_label_set_text(ui_Label_Main_Button_WiFi, "\uF1EB");
    lv_label_set_text(ui_Label_Main_Thermal_Crosshair, "\uF05B");
    lv_label_set_text(ui_Label_Menu_Back, "\uF060");
    lv_label_set_text(ui_Label_Info_Back, "\uF060");
}

void ScreenInfoLoaded(lv_event_t *e)
{
    esp_event_post(GUI_EVENTS, GUI_EVENT_REQUEST_UPTIME, NULL, 0, 0);
    esp_event_post(GUI_EVENTS, GUI_EVENT_REQUEST_FPA_AUX_TEMP, NULL, 0, 0);
}

void ButtonMainWiFiClicked(lv_event_t *e)
{
    esp_event_post(NETWORK_EVENTS, NETWORK_EVENT_OPEN_WIFI_REQUEST, NULL, 0, 0);
}

void ScreenSplashLoaded(lv_event_t * e)
{
    ui_settings_build(ui_Container_Menu);
}

void ButtonMenuSaveClicked(lv_event_t * e)
{
    lv_obj_t * Box = lv_msgbox_create(NULL);

    SettingsManager_Save();

    lv_msgbox_add_title(Box, "Settings Saved");

    lv_timer_t * Timer = lv_timer_create(MessageBox_on_Close, 1000, Box);
    lv_timer_set_repeat_count(Timer, 1);
}
