// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: PyroVision

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ScreenSplashLoaded(lv_event_t * e);
void ScreenMainLoaded(lv_event_t * e);
void ButtonMainButton4ShortClicked(lv_event_t * e);
void ButtonMainButton4LongClicked(lv_event_t * e);
void ButtonMainButton2ShortClicked(lv_event_t * e);
void ButtonMainButton2LongClicked(lv_event_t * e);
void ButtonMainButton3ShortClicked(lv_event_t * e);
void ButtonMainButton1ShortClicked(lv_event_t * e);
void ScreenMenuLoaded(lv_event_t * e);
void ButtonMenuButton4ShortClicked(lv_event_t * e);
void ScreenInfoLoaded(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
