// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: PyroVision

#include <esp_log.h>
#include <esp_event.h>

#include "ui.h"

#include "../../../application.h"
#include "../guiTask.h"
#include "../UI/ui_settings.h"
#include "../UI/ui_messagebox.h"

/** @brief LV_EVENT_KEY handler registered on the focused group object of the Main screen.
 *         Translates GUI_KEYPAD_BTN2/3/4 into button click events.
 */
static void on_main_screen_key(lv_event_t *e)
{
    switch (lv_event_get_key(e)) {
        case GUI_KEYPAD_BTN1: {
            lv_obj_send_event(ui_Button_Main_Menu, LV_EVENT_CLICKED, NULL);
            break;
        }
        case GUI_KEYPAD_BTN2: {
            lv_obj_send_event(ui_Button_Main_ROI, LV_EVENT_CLICKED, NULL);
            break;
        }
        case GUI_KEYPAD_BTN3: {
            lv_obj_send_event(ui_Button_Main_Switch, LV_EVENT_CLICKED, NULL);
            break;
        }
        case GUI_KEYPAD_BTN4: {
            lv_obj_send_event(ui_Button_Main_Save, LV_EVENT_CLICKED, NULL);
            break;
        }
        default: {
            break;
        }
    }
}

/** @brief LV_EVENT_KEY handler registered on the focused group object of the Menu screen.
 *         Translates GUI_KEYPAD_BTN4 into the Save button click.
 */
static void on_menu_screen_key(lv_event_t *e)
{
    switch (lv_event_get_key(e)) {
        case GUI_KEYPAD_BTN1: {
            lv_obj_send_event(ui_Button_Menu_Back, LV_EVENT_CLICKED, NULL);
            break;
        }
        case GUI_KEYPAD_BTN2: {
            break;
        }
        case GUI_KEYPAD_BTN3: {
            lv_obj_send_event(ui_Button_Menu_Info, LV_EVENT_CLICKED, NULL);
            break;
        }
        case GUI_KEYPAD_BTN4: {
            lv_obj_send_event(ui_Button_Menu_Save, LV_EVENT_CLICKED, NULL);
            break;
        }
        default: {
            break;
        }
    }
}

/** @brief LV_EVENT_KEY handler registered on the focused group object of the Info screen.
 *         Translates GUI_KEYPAD_BTN1 into the Back button click.
 */
static void on_info_screen_key(lv_event_t *e)
{
    switch (lv_event_get_key(e)) {
        case GUI_KEYPAD_BTN1: {
            lv_obj_send_event(ui_Button_Info_Back, LV_EVENT_CLICKED, NULL);
            break;
        }
        case GUI_KEYPAD_BTN2: {
            break;
        }
        case GUI_KEYPAD_BTN3: {
            break;
        }
        case GUI_KEYPAD_BTN4: {
            break;
        }
        default: {
            break;
        }
    }
}

/** @brief Remove the keypad group that was bound to this screen and delete it.
 */
static void on_screen_keypad_group_cleanup(lv_event_t *e)
{
    (void)e;

    lv_indev_t *p_Keypad = GUI_Task_GetKeypadIndev();

    if (p_Keypad == NULL) {
        return;
    }

    lv_group_t *p_Group = lv_indev_get_group(p_Keypad);

    lv_indev_set_group(p_Keypad, NULL);

    if (p_Group != NULL) {
        lv_group_delete(p_Group);
    }
}

void ScreenMainLoaded(lv_event_t *e)
{
    (void)e;
    Settings_Info_t Info;
    lv_indev_t *p_Keypad;
    lv_group_t *p_Group;

    SettingsManager_GetInfo(&Info);

    /* Set the symbols for the UI */
    lv_label_set_text(ui_Image_Main_WiFi, LV_SYMBOL_WIFI);
    lv_label_set_text(ui_Image_Main_SDCard, LV_SYMBOL_SD_CARD);
    lv_label_set_text(ui_Label_Main_Button_Save, LV_SYMBOL_SAVE);
    lv_label_set_text(ui_Label_Main_Button_Menu, "\uF0C9");
    lv_label_set_text(ui_Label_Main_Button_ROI, "\uE595");
    lv_label_set_text(ui_Label_Main_Button_Switch, "\uE0D8");
    lv_label_set_text(ui_Label_Main_Thermal_Crosshair, "\uF05B");
    lv_label_set_text(ui_Label_Main_Statusbar_Temperatur_Icon, "\uF2C7");
    lv_label_set_text(ui_Label_Info_Back, "\uF060");
    lv_label_set_text(ui_Label_Info_Button_Info, "\uF129");
    lv_label_set_text(ui_Label_Menu_Button_Save, LV_SYMBOL_SAVE);
    lv_label_set_text(ui_Label_Menu_Back, "\uF060");

    p_Keypad = GUI_Task_GetKeypadIndev();
    if (p_Keypad != NULL) {
        p_Group = lv_group_create();
        lv_group_add_obj(p_Group, ui_Button_Main_Menu);
        lv_indev_set_group(p_Keypad, p_Group);
    }

    /* Suppress the LVGL focus outline on the group anchor object */
    lv_obj_set_style_outline_width(ui_Button_Main_Menu, 0,
                                   static_cast<uint32_t>(LV_PART_MAIN) | static_cast<uint32_t>(LV_STATE_FOCUSED));
    lv_obj_set_style_outline_width(ui_Button_Main_Menu, 0,
                                   static_cast<uint32_t>(LV_PART_MAIN) | static_cast<uint32_t>(LV_STATE_FOCUS_KEY));

    lv_obj_remove_event_cb(ui_Button_Main_Menu, on_main_screen_key);
    lv_obj_add_event_cb(ui_Button_Main_Menu, on_main_screen_key, LV_EVENT_KEY, NULL);
    lv_obj_remove_event_cb(ui_Main, on_screen_keypad_group_cleanup);
    lv_obj_add_event_cb(ui_Main, on_screen_keypad_group_cleanup, LV_EVENT_SCREEN_UNLOAD_START, NULL);
}

void ScreenMenuLoaded(lv_event_t *e)
{
    (void)e;

    lv_indev_t *p_Keypad = GUI_Task_GetKeypadIndev();

    if (p_Keypad != NULL) {
        lv_group_t *p_Group = lv_group_create();
        lv_group_add_obj(p_Group, ui_Button_Menu_Back);
        lv_indev_set_group(p_Keypad, p_Group);
    }

    /* Suppress the LVGL focus outline on the group anchor object */
    lv_obj_set_style_outline_width(ui_Button_Menu_Back, 0,
                                   static_cast<uint32_t>(LV_PART_MAIN) | static_cast<uint32_t>(LV_STATE_FOCUSED));
    lv_obj_set_style_outline_width(ui_Button_Menu_Back, 0,
                                   static_cast<uint32_t>(LV_PART_MAIN) | static_cast<uint32_t>(LV_STATE_FOCUS_KEY));

    lv_obj_remove_event_cb(ui_Button_Menu_Back, on_menu_screen_key);
    lv_obj_add_event_cb(ui_Button_Menu_Back, on_menu_screen_key, LV_EVENT_KEY, NULL);
    lv_obj_remove_event_cb(ui_Menu, on_screen_keypad_group_cleanup);
    lv_obj_add_event_cb(ui_Menu, on_screen_keypad_group_cleanup, LV_EVENT_SCREEN_UNLOAD_START, NULL);
}

void ScreenInfoLoaded(lv_event_t *e)
{
    (void)e;
    lv_indev_t *p_Keypad = GUI_Task_GetKeypadIndev();

    if (p_Keypad != NULL) {
        lv_group_t *p_Group = lv_group_create();
        lv_group_add_obj(p_Group, ui_Button_Info_Back);
        lv_indev_set_group(p_Keypad, p_Group);
    }

    /* Suppress the LVGL focus outline on the group anchor object */
    lv_obj_set_style_outline_width(ui_Button_Info_Back, 0,
                                   static_cast<uint32_t>(LV_PART_MAIN) | static_cast<uint32_t>(LV_STATE_FOCUSED));
    lv_obj_set_style_outline_width(ui_Button_Info_Back, 0,
                                   static_cast<uint32_t>(LV_PART_MAIN) | static_cast<uint32_t>(LV_STATE_FOCUS_KEY));

    lv_obj_remove_event_cb(ui_Button_Info_Back, on_info_screen_key);
    lv_obj_add_event_cb(ui_Button_Info_Back, on_info_screen_key, LV_EVENT_KEY, NULL);
    lv_obj_remove_event_cb(ui_Info, on_screen_keypad_group_cleanup);
    lv_obj_add_event_cb(ui_Info, on_screen_keypad_group_cleanup, LV_EVENT_SCREEN_UNLOAD_START, NULL);
}

void ScreenSplashLoaded(lv_event_t *e)
{
    (void)e;
    char Buffer[64];

    snprintf(Buffer, sizeof(Buffer), "Firmware %u.%u.%u", PYROVISION_VERSION_MAJOR, PYROVISION_VERSION_MINOR, PYROVISION_VERSION_BUILD);

    lv_label_set_text(ui_Label_Splash_FirmwareVersion, Buffer);
    ui_settings_init(ui_Container_Menu);
}

void ButtonMainSaveClicked(lv_event_t *e)
{
    (void)e;
    esp_err_t Error;

    Error = GUI_Task_SaveImage();
    if (Error != ESP_OK) {
        MessageBox_ImageSaveError(Error);
    } else {
        MessageBox_ShowProgress("Image save in progress");
    }
}

void ButtonMenuSaveClicked(lv_event_t *e)
{
    (void)e;

    SettingsManager_Save();
    MessageBox_Show("Settings Saved");
}

void ButtonMainSwitchClicked(lv_event_t * e)
{
    (void)e;

    GUI_Task_ToggleCameraView();
}

void ButtonMainROIClicked(lv_event_t * e)
{
    (void)e;

	GUI_Task_ToggleROI();
}
